FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# FROM nginx:1.25.4-alpine3.18 # smaller image
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /var/www/html/
EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]