FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish \
	-c Release \
	-o /app/publish \
	--self-contained true \
	--runtime linux-musl-x64 \
    -p:AssemblyName=dotnet-app

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine
WORKDIR /app
COPY --from=build-env /app/publish .
ENV ASPNETCORE_URLS=http://*:5001
EXPOSE 5001
ENTRYPOINT ["./dotnet-app"]