# Using pre-built Angular application for ultra-fast builds
FROM alpine:3.20
RUN apk add --no-cache nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY dist/angular /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]