# Using pre-built Angular application for ultra-fast builds
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY dist/angular /var/www/html/
EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]