# https://medium.com/@RoussiAbdelghani/optimizing-java-base-docker-images-size-from-674mb-to-58mb-c1b7c911f622
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
ARG APP_USER=spring
RUN addgroup --system --gid 1001 "$APP_USER" && \
    adduser --system --uid 1001 "$APP_USER" && \
    mkdir -p /app && \
    chown -R "$APP_USER":"$APP_USER" /app
WORKDIR /app
COPY --from=build --chown=$APP_USER:$APP_USER /app/target/*.jar app.jar
USER $APP_USER
EXPOSE 8080
ENV server.port=8080
# Uncomment the line below to set the active profile
# ENV spring.profiles.active=prod 
CMD ["java", "-jar", "app.jar"]