FROM node:23-alpine3.20 AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
ENV NEXT_TELEMETRY_DISABLED=1
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run standalone

FROM node:23-alpine3.20
USER node
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
COPY --from=builder --chown=node:node /app/.next/standalone .
EXPOSE 3000
ENV PORT=3000
CMD [ "node", "server.js" ]