FROM node:18-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package*.json ./
RUN yarn --network-timeout 100000
COPY . .
RUN yarn standalone

FROM astefanutti/scratch-node
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
COPY --from=builder --chown=node:node /app/.next/standalone .
USER node
EXPOSE 3000
ENV PORT=3000
ENTRYPOINT [ "node", "server.js" ]