name: Build Dotnet Core Image

on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    builds:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build Docker Image
              run: docker build -t dotnet-core dotnet_core
