name: Build and Test Docker Images for Dotnet Core

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        uses: ./.github/workflows/build-and-test.yml
        with:
            matrix: |
                [
                  {
                    "dockerfile": "Dockerfile",
                    "folder": "dotnet_core",
                    "image_name": "dotnet_core_image",
                    "service_port": 8080,
                    "docker_port": 5001
                  },
                  {
                    "dockerfile": "Dockerfile_chiseled",
                    "folder": "dotnet_core",
                    "image_name": "dotnet_core_chiseled_image",
                    "service_port": 8081,
                    "docker_port": 5001
                  },
                  {
                    "dockerfile": "Dockerfile_self_contained",
                    "folder": "dotnet_core",
                    "image_name": "dotnet_core_self_contained_image",
                    "service_port": 8082,
                    "docker_port": 5001
                  }
                ]
