name: Build/Test Nodejs

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                include:
                    - dockerfile: "Dockerfile"
                      folder: "static_website"
                      image_name: "static_website_image"
                      service_port: 8050
                      docker_port: 3000

                    - dockerfile: "Dockerfile_alpine"
                      folder: "static_website"
                      image_name: "static_website_alpine_image"
                      service_port: 8051
                      docker_port: 80

                    - dockerfile: "Dockerfile_alpine_nonroot"
                      folder: "static_website"
                      image_name: "static_website_alpine_nonroot_image"
                      service_port: 8052
                      docker_port: 80

                    - dockerfile: "Dockerfile_busybox"
                      folder: "static_website"
                      image_name: "static_website_busybox_image"
                      service_port: 8053
                      docker_port: 3000

                    - dockerfile: "Dockerfile_nginx"
                      folder: "static_website"
                      image_name: "static_website_nginx_image"
                      service_port: 8054
                      docker_port: 80

        name: Build and Test Docker Images
        uses: ./.github/workflows/buildAndTest.yml
        with:
            dockerfile: ${{ matrix.dockerfile }}
            folder: ${{ matrix.folder }}
            image_name: ${{ matrix.image_name }}
            service_port: ${{ matrix.service_port }}
            docker_port: ${{ matrix.docker_port }}
